### ISSUE TITLE
Unable to resume normal internet connection after closing VPN connection

### ISSUE THREAD

**Issue by travs** [nstinus/nordvpn#22]
Steps to reproduce:

```sh
sudo nordvpn start ca18 # for example
ping github.com # works great
sudo nordvpn stop
ping github.com # no response
```

I've tried restarting various system services related to the network, but nothing seems to get me back online except a reboot.

Is there a dev mode I can run to look deeper, as no error appears when I stop the VPN connection.

Using the latest version (`0.1.21-1`).

**Comment by nstinus** [comment]
The nordvpn script relies on a third party to update resolv.conf. In its
simple setup it is done by openvpn-update-resolv-conf.
However, it can also use an vpnfailsafe-git, that ensures all traffic is
routed through the vnp connection. By default it doesn't restore the system
and if you stop. See https://github.com/nstinus/nordvpn/issues/14 and
https://github.com/awknapik/vpnfailsafe#16
I suspect that is your problem. See if you can remove vpnfailsafe-git.

You can run all commands in verbose mode, for example: sudo nordvpn -v start

On Aug 4, 2017 04:04, "Travis Jacobs" <notifications@github.com> wrote:

Steps to reproduce:

sudo nordvpn start ca18 // for example
ping github.com // works great
sudo nordvpn stop
ping github.com // no response

I've tried restarting various system services related to the network, but
nothing seems to get me back online except a reboot.

Is there a dev mode I can run to look deeper, as no error appears when I
stop the VPN connection.

Using the latest version (0.1.21-1).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nstinus/nordvpn/issues/22>, or mute the thread

**Comment by travs** [comment]
Ok that makes sense, and yes it is my problem.
Will track #14 now and wait for the solution there.
Thanks for the help.
